export const mockUserData = [
  {
    id: "1",
    first_name: "Ulises",
    last_name: "Mitchelson",
    email: "umitchelson0@photobucket.com",
    username: "umitchelson0",
    profilePic: "http://dummyimage.com/197x100.png/ff4444/ffffff",
    contact_number: "6441165622",
    slack: "",
    linkedIn: "https://www.linkedin.com/in/charlottedurber/",
    bio: "Donec dapibus. Duis at velit eu est congue elementum.",
    user_process: {
      user_onboarding_task_slack: true,
      user_onboarding_task_linkedin: false,
      user_onboarding_task_CodeofConduct: true,
      user_onboarding_task_tshirtsent: false,
      user_offboarding_task_feedbackrequested: false,
      user_offboarding_task_feedbackreceived: false,
      user_offboarding_task_tshirtreceived: false,
      is_completed: "false",
      timestamps: "2023-07-18T02:00:17Z",
    },
  },
  {
    id: "2",
    first_name: "Daune",
    last_name: "Vanin",
    email: "dvanin1@globo.com",
    username: "dvanin1",
    profilePic: "http://dummyimage.com/250x100.png/5fa2dd/ffffff",
    contact_number: "2212717102",
    slack: "https://www.linkedin.com/in/charlottedurber/",
    linkedIn: "https://www.linkedin.com/in/charlottedurber/",
    bio: '"Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo',
    user_process: {
      user_onboarding_task_slack: false,
      user_onboarding_task_linkedin: false,
      user_onboarding_task_CodeofConduct: false,
      user_onboarding_task_tshirtsent: false,
      user_offboarding_task_feedbackrequested: false,
      user_offboarding_task_feedbackreceived: false,
      user_offboarding_task_tshirtreceived: false,
      is_completed: "false",
      timestamps: "2023-07-18T02:00:17Z",
    },
  },
  {
    id: "3",
    first_name: "Bethanne",
    last_name: "Lowle",
    email: "blowle2@slideshare.net",
    username: "blowle2",
    profilePic: "",
    contact_number: "1614914752",
    slack: "https://www.linkedin.com/in/charlottedurber/",
    linkedIn: "https://www.linkedin.com/in/charlottedurber/",
    bio: '"Cum sociis natoque penatibus et magnis dis parturient montes',
    user_process: {
      user_onboarding_task_slack: false,
      user_onboarding_task_linkedin: false,
      user_onboarding_task_CodeofConduct: false,
      user_onboarding_task_tshirtsent: false,
      user_offboarding_task_feedbackrequested: false,
      user_offboarding_task_feedbackreceived: false,
      user_offboarding_task_tshirtreceived: false,
      is_completed: "false",
      timestamps: "2023-07-18T02:00:17Z",
    },
  },
  {
    id: "4",
    first_name: "Bennie",
    last_name: "Sute",
    email: "bsute3@amazon.com",
    username: "bsute3",
    profilePic: "",
    contact_number: "4639764789",
    slack: "",
    linkedIn: "https://www.linkedin.com/in/charlottedurber/",
    bio: '"Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio',
    user_process: {
      user_onboarding_task_slack: false,
      user_onboarding_task_linkedin: false,
      user_onboarding_task_CodeofConduct: false,
      user_onboarding_task_tshirtsent: false,
      user_offboarding_task_feedbackrequested: false,
      user_offboarding_task_feedbackreceived: false,
      user_offboarding_task_tshirtreceived: false,
      is_completed: "false",
      timestamps: "2023-07-18T02:00:17Z",
    },
  },
  {
    id: "5",
    first_name: "Kristo",
    last_name: "Jex",
    email: "kjex4@dailymail.co.uk",
    username: "kjex4",
    profilePic: "http://dummyimage.com/242x100.png/cc0000/ffffff",
    contact_number: "5413673203",
    slack: "",
    linkedIn: "https://www.linkedin.com/in/charlottedurber/",
    bio: '"Fusce lacus purus',
    user_process: {
      user_onboarding_task_slack: false,
      user_onboarding_task_linkedin: false,
      user_onboarding_task_CodeofConduct: false,
      user_onboarding_task_tshirtsent: false,
      user_offboarding_task_feedbackrequested: false,
      user_offboarding_task_feedbackreceived: false,
      user_offboarding_task_tshirtreceived: false,
      is_completed: "false",
      timestamps: "2023-07-18T02:00:17Z",
    },
  },
  {
    id: "6",
    first_name: "Galen",
    last_name: "Masdon",
    email: "gmasdon5@godaddy.com",
    username: "gmasdon5",
    profilePic: "http://dummyimage.com/206x100.png/cc0000/ffffff",
    contact_number: "9489789181",
    slack: "",
    linkedIn: "https://www.linkedin.com/in/charlottedurber/",
    bio: '"Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo',
    user_process: {
      user_onboarding_task_slack: false,
      user_onboarding_task_linkedin: false,
      user_onboarding_task_CodeofConduct: false,
      user_onboarding_task_tshirtsent: false,
      user_offboarding_task_feedbackrequested: false,
      user_offboarding_task_feedbackreceived: false,
      user_offboarding_task_tshirtreceived: false,
      is_completed: "false",
      timestamps: "2023-07-18T02:00:17Z",
    },
  },
  {
    id: "7",
    first_name: "Cherianne",
    last_name: "Sollars",
    email: "csollars6@eepurl.com",
    username: "csollars6",
    profilePic: "http://dummyimage.com/156x100.png/5fa2dd/ffffff",
    contact_number: "2567146169",
    slack: "https://www.linkedin.com/in/charlottedurber/",
    linkedIn: "https://www.linkedin.com/in/charlottedurber/",
    bio: '"Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes',
    user_process: {
      user_onboarding_task_slack: false,
      user_onboarding_task_linkedin: false,
      user_onboarding_task_CodeofConduct: false,
      user_onboarding_task_tshirtsent: false,
      user_offboarding_task_feedbackrequested: false,
      user_offboarding_task_feedbackreceived: false,
      user_offboarding_task_tshirtreceived: false,
      is_completed: "false",
      timestamps: "2023-07-18T02:00:17Z",
    },
  },
  {
    id: "8",
    first_name: "Emmy",
    last_name: "Garey",
    email: "egarey7@mit.edu",
    username: "egarey7",
    profilePic: "http://dummyimage.com/198x100.png/ff4444/ffffff",
    contact_number: "1874739097",
    slack: "https://www.linkedin.com/in/charlottedurber/",
    linkedIn: "https://www.linkedin.com/in/charlottedurber/",
    bio: '"Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero',
    user_process: {
      user_onboarding_task_slack: false,
      user_onboarding_task_linkedin: false,
      user_onboarding_task_CodeofConduct: false,
      user_onboarding_task_tshirtsent: false,
      user_offboarding_task_feedbackrequested: false,
      user_offboarding_task_feedbackreceived: false,
      user_offboarding_task_tshirtreceived: false,
      is_completed: "false",
      timestamps: "2023-07-18T02:00:17Z",
    },
  },
  {
    id: "9",
    first_name: "Spenser",
    last_name: "Ebbitt",
    email: "sebbitt8@weather.com",
    username: "sebbitt8",
    profilePic: "",
    contact_number: "8586419578",
    slack: "",
    linkedIn: "https://www.linkedin.com/in/charlottedurber/",
    bio: '"Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam',
    user_process: {
      user_onboarding_task_slack: false,
      user_onboarding_task_linkedin: false,
      user_onboarding_task_CodeofConduct: false,
      user_onboarding_task_tshirtsent: false,
      user_offboarding_task_feedbackrequested: false,
      user_offboarding_task_feedbackreceived: false,
      user_offboarding_task_tshirtreceived: false,
      is_completed: "false",
      timestamps: "2023-07-18T02:00:17Z",
    },
  },
  {
    id: "10",
    first_name: "Joella",
    last_name: "Sear",
    email: "jsear9@google.pl",
    username: "jsear9",
    profilePic: "http://dummyimage.com/177x100.png/5fa2dd/ffffff",
    contact_number: "1219542577",
    slack: "https://www.linkedin.com/in/charlottedurber/",
    linkedIn: "",
    bio: '"In tempor',
    user_process: {
      user_onboarding_task_slack: false,
      user_onboarding_task_linkedin: false,
      user_onboarding_task_CodeofConduct: false,
      user_onboarding_task_tshirtsent: false,
      user_offboarding_task_feedbackrequested: false,
      user_offboarding_task_feedbackreceived: false,
      user_offboarding_task_tshirtreceived: false,
      is_completed: "false",
      timestamps: "2023-07-18T02:00:17Z",
    },
  },
];
