export const mockUserProcessData = [
  {
    mentor: "1",
    user_onboarding_task_slack: false,
    user_onboarding_task_linkedin: true,
    user_onboarding_task_CodeofConduct: false,
    user_onboarding_task_tshirtsent: false,
    user_offboarding_task_feedbackrequested: false,
    user_offboarding_task_feedbackreceived: false,
    user_offboarding_task_tshirtreceived: false,
    is_completed: "false",
    timestamps: "2023-07-18T02:00:17Z",
  },
  {
    mentor: "2",
    user_onboarding_task_slack: false,
    user_onboarding_task_linkedin: false,
    user_onboarding_task_CodeofConduct: false,
    user_onboarding_task_tshirtsent: false,
    user_offboarding_task_feedbackrequested: false,
    user_offboarding_task_feedbackreceived: false,
    user_offboarding_task_tshirtreceived: false,
    is_completed: "false",
    timestamps: "2023-11-16T21:41:22Z",
  },
  {
    mentor: "3",
    user_onboarding_task_slack: false,
    user_onboarding_task_linkedin: false,
    user_onboarding_task_CodeofConduct: false,
    user_onboarding_task_tshirtsent: false,
    user_offboarding_task_feedbackrequested: false,
    user_offboarding_task_feedbackreceived: false,
    user_offboarding_task_tshirtreceived: false,
    is_completed: "false",
    timestamps: "2023-06-24T16:44:32Z",
  },
  {
    mentor: "4",
    user_onboarding_task_slack: false,
    user_onboarding_task_linkedin: false,
    user_onboarding_task_CodeofConduct: false,
    user_onboarding_task_tshirtsent: false,
    user_offboarding_task_feedbackrequested: false,
    user_offboarding_task_feedbackreceived: false,
    user_offboarding_task_tshirtreceived: false,
    is_completed: "false",
    timestamps: "2023-05-12T02:16:41Z",
  },
  {
    mentor: "5",
    user_onboarding_task_slack: false,
    user_onboarding_task_linkedin: false,
    user_onboarding_task_CodeofConduct: false,
    user_onboarding_task_tshirtsent: false,
    user_offboarding_task_feedbackrequested: false,
    user_offboarding_task_feedbackreceived: false,
    user_offboarding_task_tshirtreceived: false,
    is_completed: "false",
    timestamps: "2023-10-11T19:43:51Z",
  },
  {
    mentor: "6",
    user_onboarding_task_slack: false,
    user_onboarding_task_linkedin: false,
    user_onboarding_task_CodeofConduct: false,
    user_onboarding_task_tshirtsent: false,
    user_offboarding_task_feedbackrequested: false,
    user_offboarding_task_feedbackreceived: false,
    user_offboarding_task_tshirtreceived: false,
    is_completed: "false",
    timestamps: "2023-04-23T01:40:03Z",
  },
  {
    mentor: "7",
    user_onboarding_task_slack: false,
    user_onboarding_task_linkedin: false,
    user_onboarding_task_CodeofConduct: false,
    user_onboarding_task_tshirtsent: false,
    user_offboarding_task_feedbackrequested: false,
    user_offboarding_task_feedbackreceived: false,
    user_offboarding_task_tshirtreceived: false,
    is_completed: "true",
    timestamps: "2023-11-17T03:13:40Z",
  },
  {
    mentor: "8",
    user_onboarding_task_slack: false,
    user_onboarding_task_linkedin: false,
    user_onboarding_task_CodeofConduct: false,
    user_onboarding_task_tshirtsent: false,
    user_offboarding_task_feedbackrequested: false,
    user_offboarding_task_feedbackreceived: false,
    user_offboarding_task_tshirtreceived: false,
    is_completed: "false",
    timestamps: "2023-11-18T02:42:15Z",
  },
  {
    mentor: "9",
    user_onboarding_task_slack: false,
    user_onboarding_task_linkedin: false,
    user_onboarding_task_CodeofConduct: false,
    user_onboarding_task_tshirtsent: false,
    user_offboarding_task_feedbackrequested: false,
    user_offboarding_task_feedbackreceived: false,
    user_offboarding_task_tshirtreceived: false,
    is_completed: "true",
    timestamps: "2023-12-13T02:13:58Z",
  },
  {
    mentor: "10",
    user_onboarding_task_slack: false,
    user_onboarding_task_linkedin: false,
    user_onboarding_task_CodeofConduct: false,
    user_onboarding_task_tshirtsent: false,
    user_offboarding_task_feedbackrequested: false,
    user_offboarding_task_feedbackreceived: false,
    user_offboarding_task_tshirtreceived: false,
    is_completed: "true",
    timestamps: "2023-10-15T13:02:39Z",
  },
];
